
GET https://api.api-ninjas.com/v1/chucknorris
X-Api-Key: SNLyaJNPR0P1AbrU4UngtA==kyDkbZgRPDZrJLnv
#Content-Type: application/json


GET http://localhost:8000/api/v1/bitcoin/price?currency=EUR&source=ninjas
Content-Type: application/json
x-api-key: 7a3e9242-7828-46c3-aae5-dd83d3acdb72


##


GET http://localhost:8000/api/v1/bitcoin/prices
Content-Type: application/json
x-api-key: 7a3e9242-7828-46c3-aae5-dd83d3acdb72


GET http://localhost:8000/api/v1/bitcoin/sources
Content-Type: application/json
x-api-key: 7a3e9242-7828-46c3-aae5-dd83d3acdb72