[project]
name = "octo-data-gateway"
description = "Gateway for external data access"
version="0.0.1"
authors = [
    {name = "Fabricio Entringer", email = "fabricio@entringer.dev"}
]


dependencies = [
    "fastapi>=0.116.0",
    "uvicorn[standard]>=0.35.0",
    "requests>=2.32.4",
    "tinydb>=4.8.2",
    "python-json-logger>=3.3.0",
    "email_validator>=2.3.0",
    "schwifty>=2025.7.0",
    "rest-health>=0.1.1"
]

requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
    "pytest-mock>=3.14.1",
    "dnspython>=2.7.0",
    "coverage>=7.10.6",
    "pytest-cov>=6.2.1"
]


[tool.setuptools.packages.find]
where = ["."]
include = ["api*", "plugin*"]
exclude = ["log*", "assets*"]


[tool.coverage.run]
relative_files = true
source = ["app"]
omit = [
    "tests/*",
    "*/__init__.py",
    ".venv/*",
    "run.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError"
]

[build-system]
requires = ["setuptools>=72.0", "wheel"]
build-backend = "setuptools.build_meta"