
## Bitcoin Price API Requests

### Get Bitcoin Price in USD from CoinGecko
GET {{base-url}}/bitcoin/price?currency=USD&source=coingecko
Content-Type: application/json
x-api-key: {{x-api-key}}

### Get Bitcoin Price in EUR from Binance
GET {{base-url}}/bitcoin/price?currency=USD&source=binance
Content-Type: application/json
x-api-key: {{x-api-key}}

### Get Bitcoin Price from all sources
GET {{base-url}}/bitcoin/prices?currency=USD
Content-Type: application/json
x-api-key: {{x-api-key}}

### Get available Bitcoin price from CoinStats
GET {{base-url}}/bitcoin/price?currency=USD&source=coinstats
Content-Type: application/json
x-api-key: {{x-api-key}}

### Get Bitcoin Balance for addresses in USD
POST {{base-url}}/bitcoin/balance
Content-Type: application/json
x-api-key: {{x-api-key}}

{
  "addresses": [
    "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
  ],
  "fiat_currency": "USD"
}